### ISSUE TITLE
I can't see RichText styles in my next js project

### ISSUE THREAD

**Issue by beqramo** [prismicio/prismic-react#100]
Hi,

I updated RichText in admin panel but on my website it looks like kinda raw text, without any styling but I suppose I should get the same result as it is in admin panel.

Am I doing something wrong?
please help

**Comment by angeloashmore** [comment]
Hi @beqramo, could you post your code that uses `RichText` and a screenshot of what it looks like?

`<RichText>`, when used as a component, should return HTML elements. The styling will be dependent on your CSS for the page.

**Comment by beqramo** [comment]
thank you. I got it now
