### ISSUE TITLE
Expose 'type-fest' as dependency instead of devDependency

### ISSUE THREAD

**Issue by BillyBlaze** [prismicio/prismic-react#120]
Currently this package makes use of the `type-fest` package, for example [this piece of code](https://github.com/prismicio/prismic-react/blob/master/src/lib/pascalCase.ts#L1) uses the PascalCase type from that package. However the dependency of `type-fest` is set underneath [devDependencies](https://github.com/prismicio/prismic-react/blob/master/package.json#L88) while technically this should be underneath `dependencies` or in the worst case as a peerDependency.

The current situation is problematic for our build (we're using Bazel) we're getting build errors such as:

```
BUILD.bazel:6:11: in ts_project rule //packages/libs/prismic:tsconfig: target '@npm//type-fest:type-fest' is not visible from target '//packages/libs/prismic:tsconfig'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

The workaround to get this working is to add `type-fest` to our package.json as a dependency, however this is a bad practice. (e.g. mismatch in versions)

Therefor my question; Can we move this to dependencies?

**Comment by angeloashmore** [comment]
Hey @BillyBlaze, thanks for pointing this out. I've moved the type used from `type-fest` (`PascalCase`) into the package so we don't need it as a dependency. You can see the change in this PR: #121

This fix will be published in the next release which should come out early next week. I'll post here again once it's published. Thanks!

**Comment by BillyBlaze** [comment]
Hi @angeloashmore, your welcome and thanks for your quick response! Removing the dependency is even a better solution :smile:  I have updated my project and everything is good!
