### ISSUE TITLE
Error: [PrismicText] when previewing slice

### ISSUE THREAD

**Issue by bosbode** [prismicio/prismic-react#158]
When creating a new slice and adding a Key Text. I get the following error when trying to preview it:

Error: [PrismicText] The "field" prop only accepts a Rich Text or Title field's value but was provided a different type of field instead (e.g. a Key Text or Select field). You can resolve this error by rendering the field value inline without <PrismicText>.

I'm just following [this YouTube video ](https://youtu.be/jSa_uskwaE0?t=827).

Edit:
It works when using keyText in a span, like seen in the instructions. The code snippet in slicemachine doesn't reflect this.

`/* import { PrismicText } from '@prismicio/react' */
<PrismicText  field={slice.primary.buttonText} />`

**Comment by angeloashmore** [comment]
Hi @bosbode, you are correct; Slice Machine gives the wrong code snippet for Key Text fields.

As you saw in [the error message](https://github.com/prismicio/prismic-react/blob/b630f12222c754cfc9f01b5dd523c112e70e5a49/messages/prismictext-works-only-with-rich-text-and-title-fields.md), `<PrismicText>` only accepts Rich Text or Title field values. Key Text is already a plain string, so it can be used directly.

The Slice Machine team is fixing this error and will be released soon. The code snippet will look like this after the fix:

```tsx
{slice.primary.buttonText}
```

Thanks for reporting! 🙂
