### ISSUE TITLE
PrismicLink incorrectly defaulting with target _blank in rich text field

### ISSUE THREAD

**Issue by greatwitenorth** [prismicio/prismic-react#171]
### Versions

- @prismicio/react: 2.5.1
- react: 18.2.0
- node: 16.15.0

### Reproduction

Minimum reproduction can be found here:
https://github.com/greatwitenorth/roadmap-link-issue

<img width="1231" alt="Screen Shot 2023-01-23 at 11 29 09 AM" src="https://user-images.githubusercontent.com/547583/214125327-2232ca3c-e976-45e7-a6ff-3c5ee483ac03.png">

<img width="1468" alt="Screen Shot 2023-01-23 at 11 29 53 AM" src="https://user-images.githubusercontent.com/547583/214125342-7f015de8-79cb-4b92-8089-ca875f167eb9.png">

repo is `roadmap-link-issue`

At some point between v2.0.3 (the last known version which was working for me)  and v2.5.1 it looks like a decision was made to open external links in a new window by default if no target has been specified. This produces undesirable behaviour, since when a rich text field contains a link, no target is generally specified if you want the link to open in the same window.

It seems like this block of code might be contributing to the problem:
https://github.com/prismicio/prismic-react/blob/5b49ad5f9b624ed843c44f28dc3063ae8cde4bd0/src/PrismicLink.tsx#L187-L194

### Steps to reproduce
- Create a link within a rich text field. Ensure the target blank is `off`.
- Render this field in a Gatsby project using the `PrismicRichText` component
- Click on the link and it will open in a new window.

### What is expected?
- The link opening in the same window

### What is actually happening?
- The link opens in a new window.

**Comment by angeloashmore** [comment]
Hey @greatwitenorth, thanks for the report!

You're correct; `<PrismicLink>` was updated in [v2.4.0](https://github.com/prismicio/prismic-react/blob/master/CHANGELOG.md#240-2022-05-25) to automatically open external URLs in new windows. In retrospect, this was a mistake for the exact reason you explained.

The change has been revered as of [v2.5.2](https://github.com/prismicio/prismic-react/blob/master/CHANGELOG.md#252-2023-02-17). `target="_blank"` is now only automatically set if "Open in new tab" is checked.

You can install the latest version of `@prismicio/react` with the following command:

```sh
npm install --save @prismicio/react@latest
```

If this doesn't fix the issue, please let me know and I'll take another look at it. Thanks! 🙂
