### ISSUE TITLE
unsafe eval

### ISSUE THREAD

**Issue by alexanderfletcher-vgw** [prismicio/prismic-react#38]
similar to react-javascript it seems this bundle isn't csp friendly due to unsafe - eval,

a pr is up for react-javascript to fix it, can a similar thing be done here? 

https://github.com/prismicio/prismic-javascript/pull/97

Thanks!

**Comment by MarcMcIntosh** [comment]
Fixed in https://github.com/prismicio/prismic-reactjs/pull/39

**Comment by MarcMcIntosh** [comment]
Thanks :)
