### ISSUE TITLE
Typings missing from NPM publish

### ISSUE THREAD

**Issue by ryan-codingintrigue** [prismicio/prismic-react#52]
The `typings` folder appears to be missing from the published NPM package:

https://unpkg.com/browse/prismic-reactjs@1.3.0/

Not sure if this is intentional or not, given that it's in the `package.json` seems like this might me a mistake...

**Comment by cyrilchapon** [comment]
It's manually `.npmignore`d [here](https://github.com/prismicio/prismic-reactjs/blob/master/.npmignore#L132); thus making the package.json `typings` field unworking.

**Comment by ohlr** [comment]
https://github.com/prismicio/prismic-reactjs/commit/ff8a1c5a8e798a2b4e69024a1e79dc20fe2841bd
@cyrilchapon when will this be released?

**Comment by cyrilchapon** [comment]
I have no clue my friend; just quickly PRed this to get this done.

**Comment by cyrilchapon** [comment]
@ohlr ; hum; it's live actually.

**Comment by ohlr** [comment]
ah sorry I only looked at the releases here on github which are not actively maintained

**Comment by noblica** [comment]
Hey, I'm still getting this error, even thought the typings folder is there. Any idea what might be wrong, or if it's related to this?
![Screenshot from 2020-05-06 12-46-16](https://user-images.githubusercontent.com/9339019/81168696-c4095100-8f97-11ea-8360-e69e622d57bf.png)

**Comment by codingwithchris** [comment]
Any update on this? I am seeing the `typings/index.d.ts` file in the actual node modules package but my project still isn't recognizing it:

`Could not find a declaration file for module 'prismic-reactjs'`

On `v1.3.1`.

**Comment by codingwithchris** [comment]
Ahh... seeing now that this is directly related to #62 and #61.

**Comment by angeloashmore** [comment]
Hey everyone, I know this is an old issue, but here's a quick update.

`@prismicio/react` v2 was just published and is now written completely in TypeScript. Going forward, all types will be maintained alongside the source code and in `@prismicio/types`.

Thanks for your feedback!
