### ISSUE TITLE
Missing release entry for 1.3.0

### ISSUE THREAD

**Issue by hugihlynsson** [prismicio/prismic-react#53]
The [1.3.0](https://github.com/prismicio/prismic-reactjs/commit/7bb1d7474a5f0578fde1745653e4a2db3c64fa6b) commit was added 12 days ago and published to NPM but there is no release nor tag for that version.

**Comment by angeloashmore** [comment]
Hey @hugihlynsson, I'm going to close this old issue. Pushing tags is now part of the release so it should be done automatically going forward. Thanks!
