### ISSUE TITLE
Empty Paragraph throws error.

### ISSUE THREAD

**Issue by yourmediafriend** [prismicio/prismic-react#63]
RichText parser does not like empty paragraphs

`{
  "type": "paragraph",
  "text": "",
  "spans": []
},`

TypeError: Cannot read property 'length' of undefined

Could this be ignored rather than an error as we can't guarantee our content staff won't add empty paragraphs.

**Comment by MarcMcIntosh** [comment]
Hi @yourmediafriend 
I'm retying to create this issue in a unit test, can you provide more information in the PR above?

**Comment by angeloashmore** [comment]
Hey @yourmediafriend, I'm cleaning up old issues so I'm going to close this. If this is still an issue, please comment and I can re-open. Thanks!
