### ISSUE TITLE
linkResolver typings

### ISSUE THREAD

**Issue by YoannDelpierre** [prismicio/prismic-react#68]
Hi, it seems the doc argument in `linkResolver` has been removed between 1.3.1 and 1.3.2

https://github.com/prismicio/prismic-reactjs/commit/f8e19de43192e9390b8ba25e61a6438624051ab4#diff-b52768974e6bc0faccb7d4b75b162c99R54

Based on the documentation, we should have a document in argument https://github.com/prismicio/prismic-reactjs#basic-example

Why did you remove it ?

**Comment by angeloashmore** [comment]
Hey @YoannDelpierre, I know this is an old issue, but here's a quick update.

`@prismicio/react` v2 was just published and is now written completely in TypeScript. Going forward, all types will be maintained alongside the source code and in `@prismicio/types`.

Thanks for your feedback!
