### ISSUE TITLE
Please push the tags

### ISSUE THREAD

**Issue by Levino** [prismicio/prismic-react#72]
Tag `1.3.1` and `1.3.2` are missing. I guess you have tagged the code before release but forgot to push the tags to github. Please do so, I need to compare the versions.

**Comment by Levino** [comment]
The reason for the missing tags is that this package is published via a CD pipeline. You need to push back the tags after publishing. So what about that?

**Comment by angeloashmore** [comment]
@Levino I'm going to close this issue since v2 is now out. Publishing tags is now part of the publish script so it will happen automatically going forward. Thanks!
