### ISSUE TITLE
Stop maintaining type defs

### ISSUE THREAD

**Issue by Levino** [prismicio/prismic-react#74]
It is [not best practice](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) to maintain types if projects are not written in TypeScript:
> If your types are generated by your source code, publish the types with your source code. Both TypeScript and JavaScript projects can generate types via --declaration.
> 
> Otherwise, we recommend submitting the types to DefinitelyTyped, which will publish them to the @types organization on npm.

If you move your types there, you will get tests for the types and strong support by TypeScript experts. Maintaining types with a JS project is very error prone.

**Comment by angeloashmore** [comment]
Hey @Levino, I know this is an old issue, but here's a quick update.

`@prismicio/react` v2 was just published and is now written completely in TypeScript. Going forward, all types will be maintained alongside the source code and in `@prismicio/types`.

Thanks for your feedback!
