### ISSUE TITLE
Firefox and Chrome don't have same nesting order for links with labels.

### ISSUE THREAD

**Issue by Matthaios** [prismicio/prismic-react#82]
Hi,
I noticed a problem where RichText is rendering components differently for Firebox vs Chrome. Already noticed this on 2 clients' websites. Basically if you add a label to the link in Rich Text it will nest them differently depending on the browser.

From Firefox:
![image](https://user-images.githubusercontent.com/6664753/113664786-aadbb980-96ac-11eb-917f-5a700a0b3cfc.png)
From Chrome:
![image](https://user-images.githubusercontent.com/6664753/113664858-c9da4b80-96ac-11eb-9fe9-e6e923d16a8d.png)

 
Currently resolving it by adding click event handlers to buttons that have links inside.

**Comment by lihbr** [comment]
Hey @Matthaios, thank you so much for reporting that we'll investigate!

cc @a-trost, @hypervillain

**Comment by angeloashmore** [comment]
Hey @Matthaios, this is an old issue but here's a quick update.

We just released `@prismicio/react` v2 which uses a new Rich Text renderer. The issue you described should not happen with the new package, but please let me know if you still experience it.

Thanks!
